In [1]:
import pandas as pd
import numpy as np

In [3]:
pwd

'D:\\LIDC_GDRO\\notebooks'

In [11]:
cluster_all = pd.read_csv('D:\\LIDC_GDRO\\cluster_results\\all_clusters.csv', index_col = False)
cluster_all = cluster_all.iloc[:,1:]

In [12]:
cluster_all.head(3)

cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  cluster_5  \
0          3          3          3          3          3          3   
1          2          2          2          2          2          2   
2          3          3          3          3          3          3   

   cluster_6  cluster_7  cluster_8  cluster_9  ...  cluster_20  cluster_21  \
0          3          3          3          3  ...           3           3   
1          2          2          2          2  ...           2           2   
2          3          3          3          3  ...           3           3   

   cluster_22  cluster_23  cluster_24  cluster_25  cluster_26  cluster_27  \
0           3           3           3           3           3           3   
1           2           2           2           2           2           2   
2           3           3           3           3           3           3   

   cluster_28  cluster_29  
0           3           3  
1           2           2  
2           3           3  

[3 rows x 30 columns]

In [16]:
cluster_all.iloc[0].values

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [18]:
all_arrays = []
for i in range(len(cluster_all)):
    all_arrays.append(cluster_all.iloc[i].values)

In [22]:
#https://stackoverflow.com/questions/38504737/calculate-percentage-of-count-for-a-list-of-arrays

import numpy_indexed as npi
arrs = all_arrays
idx = [np.ones(len(a))*i for i, a in enumerate(arrs)]
(rows, cols), table = npi.count_table(np.concatenate(idx), np.concatenate(arrs))
table = table / table.sum(axis=1, keepdims=True)
print(table * 100)

[[  0.   0.   0. 100.]
 [  0.   0. 100.   0.]
 [  0.   0.   0. 100.]
 ...
 [  0. 100.   0.   0.]
 [  0.   0. 100.   0.]
 [  0. 100.   0.   0.]]


C:\Users\YWANG192\Anaconda3\envs\pytorch\lib\site-packages\numpy_indexed\funcs.py:69: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  np.add.at(table, inverses, 1)


In [24]:
max_percentage = []

for i in range(len(table)):
    max_percentage.append(max(table[i]))

In [25]:
max_percentage

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.5666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 0.5333333333333333,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.8666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9,
 0.9666666666666667,
 1.0,
 0.9,
 1.0,
 0.6666666666666666,
 1.0,
 0.5333333333333333,
 0.8666666666666667,
 0.5333333333333333,
 0.8333333333333334,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.5666666666666667,
 1.0,
 0.9,
 1.0,
 1.0,
 1.0,
 0.7,
 1.0,
 1.0,
 1.0,
 0.7666666666666667,
 1.0,
 0.9666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 0.6,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.6333333333333333,
 1.0,
 1.0,
 0.6666666666666666,
 1.0,
 0.9333333333333333,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9666666666666667,
 1.0,
 1.0,
 0.7,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.7666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9333333333333333,
 1.0,
 1.0,
 0.8333333333333334,
 0.8333333

In [28]:
from collections import Counter
Counter(max_percentage)

Counter({1.0: 1164,
         0.5666666666666667: 15,
         0.5333333333333333: 14,
         0.8666666666666667: 20,
         0.9: 29,
         0.9666666666666667: 54,
         0.6666666666666666: 10,
         0.8333333333333334: 26,
         0.7666666666666667: 20,
         0.7: 15,
         0.6: 11,
         0.6333333333333333: 18,
         0.9333333333333333: 54,
         0.7333333333333333: 15,
         0.8: 19,
         0.5: 4})

In [ ]:
cluster_all['max_percentage']